apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secret-tester
  labels:
    app.kubernetes.io/name: secret-tester
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: secret-tester
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
