// Scheduled platform backup and restore verification (#283, design 13).
//
// The same shape ADR-54 already proved for reconciliation: systemd USER
// timers, so the units inherit the operator's kubeconfig, $HERMES_HOME
// and pulumi login and need no root.
//
// Two timers, not one, because they answer different questions and fail
// differently. The backup timer asks "is there a recent restore point".
// The VERIFY timer asks "does one of them actually restore" - and until
// something runs it on a schedule, `restorable` is a state a fleet
// reaches once, by hand, and then drifts away from silently while every
// surface keeps showing the last verification it ever did.

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { CliError, HG_HOME, log, ok } from "../lib.ts";

export interface TimerConfig {
  /** Where scaffolded backups land. A host path, never published. */
  destination: string;
  /** systemd OnCalendar for the backup itself. */
  backupSchedule: string;
  /** systemd OnCalendar for restore verification. Deliberately rarer:
   * a verification restores into the live cluster, so it is a real
   * operation with real disruption, not a poll. */
  verifySchedule: string;
  /** Cloud sink for every scheduled run (`gs://...` or `emulated`).
   * Absent = local scaffold only, exactly as before. */
  sink?: string;
  /** Writer SA the scheduled runs impersonate (#297's identity split) -
   * baked into the units as env because a timer has no interactive env. */
  writerSa?: string;
  /** Reader SA the weekly verification fetches with - the identity a
   * clean server would use, which is the whole point of verifying. */
  readerSa?: string;
}

export const DEFAULT_TIMERS: Omit<TimerConfig, "destination"> = {
  backupSchedule: "*-*-* 02:30:00",
  // Weekly. Often enough that `restorable` cannot quietly age into
  // fiction; rare enough that it is not routinely disrupting the fleet.
  verifySchedule: "Sun *-*-* 04:00:00",
};

function userUnitDir(): string {
  return path.join(os.homedir(), ".config", "systemd", "user");
}

export function backupUnitFiles(
  cfg: TimerConfig,
  entry: { bun: string; main: string },
): Record<string, string> {
  const run = `${entry.bun} ${entry.main}`;
  const sinkArg = cfg.sink ? ` --sink ${cfg.sink}` : "";
  // A destination server's verbs address the REAL cluster, not the k3d
  // loop - the installing session's HG_KUBE_CONTEXT is baked in so a
  // timer tick sees the same cluster the operator did.
  const kctx = process.env["HG_KUBE_CONTEXT"];
  const writerEnv =
    (cfg.writerSa ? `\nEnvironment=HG_BACKUP_WRITER_SA=${cfg.writerSa}` : "") +
    (cfg.readerSa ? `\nEnvironment=HG_RESTORE_READER_SA=${cfg.readerSa}` : "") +
    (kctx ? `\nEnvironment=HG_KUBE_CONTEXT=${kctx}` : "");
  // systemd user units get a minimal PATH that excludes ~/.local/bin -
  // where bun AND gcloud live on a bootstrapped server. The reconcile
  // unit learned this first (reconcile.ts, same line shape); the backup
  // units failed silently for two nights when gcloud fell off the
  // default PATH, which is exactly the failure the units exist to avoid.
  const pathEnv = `\nEnvironment=PATH=${path.dirname(entry.bun)}:/usr/local/bin:/usr/bin:/bin`;
  return {
    "hermes-platform-backup.service": `# Generated by \`hg platform backup install-timer\` - edit the config, not this file.
[Unit]
Description=Harness Hg platform backup

[Service]
Type=oneshot
Environment=HERMES_GITOPS_HOME=${HG_HOME}${writerEnv}${pathEnv}
ExecStart=${run} platform backup create --to ${cfg.destination}${sinkArg}
# A backup that runs long is still a backup; one that is killed halfway
# leaves a scaffold directory with no manifest, which reads as a backup
# that exists and cannot be restored.
TimeoutStartSec=3600
`,
    "hermes-platform-backup.timer": `# Generated by \`hg platform backup install-timer\`.
[Unit]
Description=Harness Hg platform backup

[Timer]
OnCalendar=${cfg.backupSchedule}
# Catch up after the host was off. A missed window is exactly when the
# restore point matters most.
Persistent=true
AccuracySec=1min
Unit=hermes-platform-backup.service

[Install]
WantedBy=timers.target
`,
    "hermes-restore-verify.service": `# Generated by \`hg platform backup install-timer\`.
[Unit]
Description=Harness Hg restore verification

[Service]
Type=oneshot
Environment=HERMES_GITOPS_HOME=${HG_HOME}${writerEnv}${pathEnv}
# Verifies the NEWEST backup by restoring it and proving the result.
# This is a real restore against the live cluster - it is what turns
# \`available\` into \`restorable\`, and there is no way to learn that
# without doing it.
ExecStart=${run} platform verify-restore --from ${cfg.destination}${sinkArg}
TimeoutStartSec=5400
`,
    "hermes-restore-verify.timer": `# Generated by \`hg platform backup install-timer\`.
[Unit]
Description=Harness Hg restore verification

[Timer]
OnCalendar=${cfg.verifySchedule}
Persistent=true
AccuracySec=5min
Unit=hermes-restore-verify.service

[Install]
WantedBy=timers.target
`,
  };
}

/** The newest scaffolded backup under `root`, or null. Directory names
 * are timestamps, so lexicographic order is chronological - the same
 * property the retention prune relies on. */
export function newestBackup(root: string): string | null {
  if (!fs.existsSync(root)) return null;
  const dirs = fs
    .readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.startsWith("hg-"))
    .map((d) => d.name)
    .sort();
  const newest = dirs[dirs.length - 1];
  return newest ? path.join(root, newest) : null;
}

/** How stale the backup and its verification are, for the surfaces that
 * report lateness. `null` means never, which is not the same as old. */
export function windowStatus(
  now: Date,
  lastBackupAt: string | null,
  lastVerifiedAt: string | null,
  backupWindowHours = 26,
  verifyWindowDays = 8,
): { backup: "current" | "late" | "never"; verify: "current" | "late" | "never" } {
  const hours = (iso: string) => (now.getTime() - Date.parse(iso)) / 3_600_000;
  return {
    backup: !lastBackupAt ? "never" : hours(lastBackupAt) > backupWindowHours ? "late" : "current",
    verify: !lastVerifiedAt ? "never" : hours(lastVerifiedAt) / 24 > verifyWindowDays ? "late" : "current",
  };
}

export function installBackupTimers(cfg: TimerConfig, opts: { enable: boolean }): void {
  const bun = Bun.which("bun");
  if (!bun) throw new CliError("bun not found on PATH - the timers would fail on every tick");
  if (!path.isAbsolute(cfg.destination)) {
    throw new CliError("--to must be an absolute path: a timer has no working directory to resolve against");
  }
  fs.mkdirSync(cfg.destination, { recursive: true });
  const main = path.resolve(import.meta.dir, "..", "main.ts");
  const dir = userUnitDir();
  fs.mkdirSync(dir, { recursive: true });
  const units = backupUnitFiles(cfg, { bun, main });
  for (const [name, body] of Object.entries(units)) fs.writeFileSync(path.join(dir, name), body);
  fs.writeFileSync(path.join(HG_HOME, "backup-timers.json"), `${JSON.stringify(cfg, null, 2)}\n`);
  ok(`wrote ${dir}/hermes-{platform-backup,restore-verify}.{service,timer}`);
  const sysd = (args: string[]) => {
    const r = Bun.spawnSync(["systemctl", "--user", ...args], { stdout: "pipe", stderr: "pipe" });
    if ((r.exitCode ?? 1) !== 0) {
      throw new CliError(`systemctl --user ${args.join(" ")} failed: ${r.stderr.toString().trim()}`);
    }
  };
  sysd(["daemon-reload"]);
  if (opts.enable) {
    sysd(["enable", "--now", "hermes-platform-backup.timer"]);
    sysd(["enable", "--now", "hermes-restore-verify.timer"]);
    ok("timers enabled (systemctl --user list-timers 'hermes-*')");
  } else {
    log("units written but not enabled - rerun with --enable");
  }
}
