"""#660 / ADR 0164: every workload-bearing resource the canonical charts
render carries the plane + component labels, asserted against the
committed goldens (regenerated by render-test.sh --update, so this test
is the drift alarm if a new template forgets the labels)."""

from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
GOLDEN = REPO_ROOT / "plugin" / "tests" / "chart" / "golden"
PLANES = yaml.safe_load((REPO_ROOT / "control-plane" / "planes.yaml").read_text())
PLANE_KEY = PLANES["labels"]["plane"]

KINDS = {"Deployment", "StatefulSet", "Service", "ConfigMap", "CronJob", "Job", "Secret"}


def test_every_golden_resource_carries_the_plane_label():
    missing = []
    for gf in sorted(GOLDEN.glob("*.yaml")):
        for doc in yaml.safe_load_all(gf.read_text()):
            if not isinstance(doc, dict) or doc.get("kind") not in KINDS:
                continue
            meta = doc.get("metadata") or {}
            labels = meta.get("labels") or {}
            if PLANE_KEY not in labels:
                missing.append(f"{gf.name}: {doc['kind']}/{meta.get('name')}")
    assert not missing, (
        "resources rendered without the plane label (add it at the resource-level "
        "labels: block and regenerate goldens):\n  " + "\n  ".join(missing)
    )


def test_plane_values_are_the_two_planes():
    seen = set()
    for gf in sorted(GOLDEN.glob("*.yaml")):
        for doc in yaml.safe_load_all(gf.read_text()):
            if isinstance(doc, dict):
                v = ((doc.get("metadata") or {}).get("labels") or {}).get(PLANE_KEY)
                if v:
                    seen.add(v)
    assert seen <= {"control-plane", "workload"}, seen


FOLDER_OF_PLANE = {"control-plane": "Control Plane", "workload": "Workloads"}


def test_dashboard_folders_follow_the_plane():
    """#663 / ADR 0166: every dashboard ConfigMap carries grafana_folder,
    and the folder is a function of the plane - provisioning owns the
    separation, so a dashboard cannot land in the wrong folder without
    failing here."""
    wrong = []
    for gf in sorted(GOLDEN.glob("*.yaml")):
        for doc in yaml.safe_load_all(gf.read_text()):
            if not isinstance(doc, dict) or doc.get("kind") != "ConfigMap":
                continue
            meta = doc.get("metadata") or {}
            labels = meta.get("labels") or {}
            if labels.get("grafana_dashboard") != "1":
                continue
            plane = labels.get(PLANE_KEY)
            folder = (meta.get("annotations") or {}).get("grafana_folder")
            want = FOLDER_OF_PLANE.get(plane)
            if folder != want:
                wrong.append(f"{gf.name}: {meta.get('name')} plane={plane} folder={folder!r} (want {want!r})")
    assert not wrong, "dashboards in the wrong (or no) Grafana folder:\n  " + "\n  ".join(wrong)
