// Pure projection: tokens.json object -> theme.css text. Shared by the
// gen-theme script and the drift test so the two can never disagree.
type Tokens = {
  colors: Record<string, { light: string; dark: string }>;
  shadows: Record<string, { light: string; dark: string }>;
  layers: Record<string, number>;
  type: { display: string; body: string };
  /** The brand faces (ADR-105): rendered as @font-face over the same-origin
   * fonts asset route. Absolute path - one URL serves the standalone shell
   * and the Hermes host. */
  fonts: { route: string; faces: { family: string; style: string; weight: string; file: string }[] };
  typeScale: Record<string, string>;
  lineHeights: Record<string, string>;
  tracking: Record<string, string>;
  motion: Record<string, string>;
  measures: Record<string, string>;
  radius: string;
  radii: Record<string, string>;
  space: Record<string, string>;
  chrome: Record<string, string>;
  kindHues: Record<string, string>;
  capHues: Record<string, string>;
  shapePalette: Record<string, { stroke: string; fill: string }>;
  /** The Astryx token bridge: Astryx theme var name -> the Nexus token
   * that must paint it (emitted as `--<name>: var(--<token>)`). One
   * declaration serves both themes - the referenced token already flips
   * in the dark block, and the unlayered .nx-root rule beats the
   * neutral theme's @layer-ed defaults by cascade. */
  astryxBridge: Record<string, string>;
};

export function renderTheme(tokens: Tokens): string {
  const block = (mode: "light" | "dark") =>
    [
      ...Object.entries(tokens.colors).map(([n, v]) => `  --${n}: ${v[mode]};`),
      ...Object.entries(tokens.shadows).map(([n, v]) => `  --${n}: ${v[mode]};`),
    ].join("\n");

  const constants = [
    ...Object.entries(tokens.layers).map(([n, z]) => `  --nx-z-${n}: ${z};`),
    `  --nx-display: ${tokens.type.display};`,
    `  --nx-body: ${tokens.type.body};`,
    ...Object.entries(tokens.typeScale).map(([n, v]) => `  --fs-${n}: ${v};`),
    ...Object.entries(tokens.lineHeights).map(([n, v]) => `  --lh-${n}: ${v};`),
    ...Object.entries(tokens.tracking).map(([n, v]) => `  --track-${n}: ${v};`),
    ...Object.entries(tokens.motion).map(([n, v]) => `  --${n}: ${v};`),
    ...Object.entries(tokens.measures).map(([n, v]) => `  --nx-${n}: ${v};`),
    `  --radius: ${tokens.radius};`,
    ...Object.entries(tokens.radii).map(([n, v]) => `  --radius-${n}: ${v};`),
    ...Object.entries(tokens.space).map(([n, v]) => `  --sp-${n}: ${v};`),
    ...Object.entries(tokens.chrome).map(([n, v]) => `  --nx-${n}: ${v};`),
    ...Object.entries(tokens.kindHues).map(([k, hue]) => `  --kind-${k}: ${hue};`),
    ...Object.entries(tokens.capHues).map(([k, hue]) => `  --cap-${k}: ${hue};`),
    ...Object.entries(tokens.shapePalette).flatMap(([n, v]) => [
      `  --shp-${n}-stroke: ${v.stroke};`,
      `  --shp-${n}-fill: ${v.fill};`,
    ]),
    ...Object.entries(tokens.astryxBridge).map(([n, t]) => `  --${n}: var(--${t});`),
  ].join("\n");

  const fontFaces = tokens.fonts.faces
    .map(
      (f) => `@font-face {
  font-family: "${f.family}";
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("${tokens.fonts.route}${f.file}") format("woff2");
}`,
    )
    .join("\n");

  // Reduced motion collapses the motion TOKENS, so every transition that
  // rides --ease-* is gated without a per-rule media query.
  const reducedMotion = Object.keys(tokens.motion)
    .map((n) => `  --${n}: 0s;`)
    .join("\n");

  return `/* GENERATED by scripts/gen-theme.ts from design/tokens.json - do not edit. */
${fontFaces}
.nx-root {
${block("light")}
${constants}
  color-scheme: light;
}
.nx-root[data-nx-theme="dark"] {
${block("dark")}
  color-scheme: dark;
}
@media (prefers-reduced-motion: reduce) {
  .nx-root {
${reducedMotion}
  }
}
`;
}
