apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-event-router.service" . }}-code
  labels:
    hermes-gitops.factorylevel.dev/plane: control-plane
    hermes-gitops.factorylevel.dev/component: event-router
    app.kubernetes.io/name: hermes-event-router
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  router.ts: |
{{ .Files.Get "files/router.ts" | indent 4 }}
