apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: {{ .Release.Namespace }}
  labels:
    hermes-gitops.factorylevel.dev/plane: control-plane
    hermes-gitops.factorylevel.dev/component: wiki
    app.kubernetes.io/name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wiki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wiki
    spec:
      containers:
        - name: wiki
          image: {{ .Values.image }}
          ports:
            - {name: http, containerPort: 8080}
          readinessProbe:
            httpGet: {path: /version, port: http}
          resources:
            requests: {cpu: 10m, memory: 32Mi}
            limits: {memory: 128Mi}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
