#!/usr/bin/env python3
"""Derive the platform version from conventional commits, and render the docs badge.

There are no tags and no releases in this repository, and every package is
`0.1.0`. A hand-maintained version string would be a lie within a week, so the
version is COMPUTED from the commit history instead — the same rule
semantic-release applies, run over `git log`:

    feat:            -> minor
    fix: / perf:     -> patch
    `!` or BREAKING  -> major, except below 1.0.0 where it is a minor
    anything else    -> no bump

Pre-1.0 semantics are deliberate: while the major is 0 a breaking change bumps
the minor, because 0.x is the range that is allowed to break. The platform has
not declared 1.0.

Output:
    v0.Y.Z              on a commit with an exact tag  (a release)
    v0.Y.Z-dev+<sha>    anywhere else                  (unreleased docs)

So a reader can always tell which repository state the docs describe, and can
always tell a release from a working build.

Usage:
    python3 infra/scripts/derive-version.py            # write the badge partial
    python3 infra/scripts/derive-version.py --check    # fail if it is stale
    python3 infra/scripts/derive-version.py --print    # just the version string
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "overrides" / "partials" / "hg-version.html"

# `type(optional scope)!: subject`
HEADER = re.compile(r"^(?P<type>[a-z]+)(?:\([^)]*\))?(?P<bang>!)?:")


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def base_tag() -> tuple[str | None, tuple[int, int, int]]:
    """The newest reachable `vX.Y.Z` tag and the version it names, if any.

    A repository that starts from a snapshot (the public tree is one commit
    of a longer private history) carries its inherited version as a tag on
    that commit; the replay below then counts only what came after it."""
    try:
        tag = git("describe", "--tags", "--abbrev=0", "--match", "v[0-9]*")
    except subprocess.CalledProcessError:
        return None, (0, 0, 0)
    m = re.match(r"^v(\d+)\.(\d+)\.(\d+)$", tag)
    if not m:
        return None, (0, 0, 0)
    return tag, (int(m.group(1)), int(m.group(2)), int(m.group(3)))


def derive() -> tuple[int, int, int]:
    """Replay the history and return the version it implies."""
    # %x1f separates fields, %x1e separates commits: subjects and bodies both
    # contain newlines, so no line-oriented split is safe here.
    tag, (major, minor, patch) = base_tag()
    rng = [f"{tag}..HEAD"] if tag else []
    log = git("log", "--reverse", "--pretty=%s%x1f%b%x1e", *rng)
    for entry in log.split("\x1e"):
        if not entry.strip():
            continue
        subject, _, body = entry.strip().partition("\x1f")
        m = HEADER.match(subject.strip())
        if not m:
            continue
        breaking = bool(m.group("bang")) or "BREAKING CHANGE" in body
        kind = m.group("type")
        if breaking:
            # Below 1.0.0, breaking is a minor: 0.x is the range that may break.
            if major == 0:
                minor, patch = minor + 1, 0
            else:
                major, minor, patch = major + 1, 0, 0
        elif kind == "feat":
            minor, patch = minor + 1, 0
        elif kind in ("fix", "perf"):
            patch += 1
    return major, minor, patch


def version_string() -> tuple[str, bool]:
    major, minor, patch = derive()
    base = f"v{major}.{minor}.{patch}"
    try:
        git("describe", "--tags", "--exact-match", "HEAD")
        return base, True
    except subprocess.CalledProcessError:
        return f"{base}-dev+{git('rev-parse', '--short', 'HEAD')}", False


def render(version: str, released: bool) -> str:
    repo = "https://github.com/factory-level/harness-hg"
    href = f"{repo}/releases" if released else f"{repo}/commits/main"
    title = (
        "Tagged release of the Harness Hg platform"
        if released
        else "Unreleased docs, built from this commit. Not a tagged release"
    )
    return f"""<!-- GENERATED by infra/scripts/derive-version.py — do not edit by hand.
     Run `make version` to regenerate; `make version-drift` fails on stale. -->
<a class="hg-version" href="{href}" title="{title}" rel="noopener">
  <span class="hg-version__tier">beta</span>
  <span class="hg-version__num">{version}</span>
</a>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="show", action="store_true")
    args = ap.parse_args()

    version, released = version_string()
    if args.show:
        print(version)
        return

    content = render(version, released)
    if args.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != content:
            sys.exit(
                f"version: {OUT.relative_to(ROOT)} is stale "
                f"(history implies {version}) — run `make version`"
            )
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({version})")


if __name__ == "__main__":
    main()
