#!/usr/bin/env python3
"""Generate _docs/wiki/reference/cli/ from the CLI's command manifest.

Same shape as generate-schema-docs.py, and for the same reason: a hand-written
CLI reference drifts the moment someone adds a flag, and nothing notices. The
manifest (cli/src/commands.ts) is the same data main.ts derives its parser and
usage output from, so these pages cannot describe a flag the CLI does not
parse. One page per top-level command, gcloud-style, plus an index.

Three things are checked, not one:

1. The dispatch switch in main.ts and the manifest must name EXACTLY the same
   commands, in both directions. (The old check matched substrings across the
   whole usage blob, which let four commands ship undocumented.)
2. Every boolean `flags.has("--x")` literal in main.ts must be a boolean flag
   somewhere in the manifest, and vice versa. Global to the CLI, not
   per-command: flag parsing is centralized and case blocks forward supersets,
   so a static per-command mapping would be guesswork. Value flags need no
   check here — main.ts derives VALUE_FLAGS from the manifest, so an
   undocumented one fails to parse (cli/tests/main-flags.test.ts).
3. Every environment variable read anywhere under cli/src must have an entry
   in ENV_DOCS below. A new variable fails the gate until someone writes one
   line about it.

Usage:
    python3 infra/scripts/generate-cli-docs.py
    python3 infra/scripts/generate-cli-docs.py --check
"""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CLI = ROOT / "cli"
MAIN = CLI / "src" / "main.ts"
OUT_DIR = ROOT / "_docs" / "wiki" / "reference" / "cli"

# Boolean flags every command accepts; documented in the index preamble, so
# they are exempt from the per-command boolean coverage check.
GLOBAL_FLAGS = {"--json", "--help"}

# Environment variables the CLI reads, and what each one is for. Keyed by the
# exact name; the generator fails if cli/src reads one that is missing here, or
# if an entry here is no longer read anywhere.
ENV_DOCS: dict[str, str] = {
    "HERMES_GITOPS_HOME": "The CLI's state directory. Default `~/.hermes-gitops`.",
    "HG_KUBE_CONTEXT": "Overrides the kube context (default `k3d-hermes-gitops-cli`).",
    "HG_EVAL_TOKEN": "The Nexus eval publish token. Read from the environment or `--token-file`, never from argv, so it cannot land in shell history.",
    "HG_CF_ACCESS_CLIENT_ID": "Cloudflare Access service-token id, when the control plane sits behind Access.",
    "HG_CF_ACCESS_CLIENT_SECRET": "Cloudflare Access service-token secret.",
    "HG_BACKUP_WRITER_SA": "Service account impersonated to WRITE platform backups to the sink.",
    "HG_RESTORE_READER_SA": "Service account impersonated to READ backups back. Separate from the writer on purpose — restore is verified with an identity that cannot have written the backup.",
    "HG_GRAFANA_ANON_VIEWER": "Treat Grafana as anonymously readable when proving observability.",
    "HG_DISCORD_BOT_TOKEN": "Bot token for the live ChatOps legs of `communication prove`.",
    "HG_DISCORD_SANDBOX_CHANNEL": "Channel id the live ChatOps legs are allowed to post into.",
    "HG_DISCORD_API_BASE": "Overrides the Discord API base, for testing against a fake.",
    "HG_RECONCILE_LOCK": "Path to the reconciler's flock. A run is skipped, not queued, while it is held.",
    "HG_PROOFS_DIR": "Where `ProofResult` documents are written.",
    "CLOUDFLARE_API_TOKEN": "The Cloudflare API token used by the `edge` verbs.",
}

BANNER = """<!-- GENERATED by infra/scripts/generate-cli-docs.py — do not edit by hand.
     Run `make cli-docs` after changing cli/src/commands.ts; `make cli-docs-drift` fails on stale. -->

"""

INDEX_INTRO = """# CLI reference

**What this page tells you:** every command `hg` accepts, and where each one's full page is.

These pages are generated from the same manifest the CLI builds its parser from. They cannot
describe a flag that does not parse. If a command here does not work, the bug is in the CLI.

`hg` is an operator tool. Nothing in the running system calls it.

## Reading the output

- **`--json` prints exactly one JSON document on stdout.** Narration goes to stderr. That is
  the contract for scripting.
- **A proof command emits a `ProofResult`:** one row per numbered check. A check that could
  not run reads `unknown`. It never reads as a pass.

See [Testing](../../platform/testing.md) for what the proofs establish.

## Commands

"""

INDEX_TAIL = """
No command takes a secret as an argument. A credential comes from the environment or from a
file named by a flag. See [Secrets](../../platform/secrets.md).
"""


def manifest() -> list[dict]:
    """The command manifest, as the CLI itself dumps it."""
    proc = subprocess.run(
        ["bun", "src/commands.ts"],
        cwd=CLI,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if proc.returncode != 0:
        sys.exit(f"cli-docs: `bun src/commands.ts` exited {proc.returncode}\n{proc.stderr}")
    return json.loads(proc.stdout)


def dispatch_commands() -> set[str]:
    """Top-level `case` labels in main.ts's command switch."""
    src = MAIN.read_text()
    start = src.index("switch (cmd)")
    # The switch runs to the end of the dispatch function; scanning to the first
    # column-0 close brace is enough and keeps this dependency-free.
    end = src.index("\n}", start)
    body = src[start:end]
    return set(re.findall(r'^\s{4}case "([a-z][a-z-]*)"', body, re.M))


def env_vars() -> set[str]:
    """Every environment variable read under cli/src."""
    found: set[str] = set()
    for path in (CLI / "src").rglob("*.ts"):
        text = path.read_text()
        found |= set(re.findall(r"(?:process|Bun)\.env\.([A-Z][A-Z0-9_]*)", text))
        found |= set(re.findall(r"(?:process|Bun)\.env\[\"([A-Z][A-Z0-9_]*)\"\]", text))
    # Set by the runtime, not by an operator — not part of the interface.
    return found - {"NODE_ENV", "HOME", "PATH", "CI", "TERM", "SHELL", "USER", "PWD"}


def check_coverage(commands: list[dict]) -> None:
    # The loop gate: every command declares its journey.
    # "No loop, no merge" — this runs under `make cli-docs-drift`, a PR gate.
    unlooped = [c["name"] for c in commands if not c.get("loops")]
    if unlooped:
        sys.exit("cli-docs: commands with no `loops` in commands.ts (no loop, no merge): " + ", ".join(sorted(unlooped)))

    names = {c["name"] for c in commands}
    dispatched = dispatch_commands()
    if names != dispatched:
        msg = []
        if dispatched - names:
            msg.append("dispatched in main.ts but missing from commands.ts:\n  " + "\n  ".join(sorted(dispatched - names)))
        if names - dispatched:
            msg.append("in commands.ts but not dispatched in main.ts:\n  " + "\n  ".join(sorted(names - dispatched)))
        sys.exit("cli-docs: the manifest and the dispatch switch disagree —\n" + "\n".join(msg))

    manifest_bools = {
        f["name"]
        for c in commands
        for s in c["subs"]
        for f in s.get("flags") or []
        if "value" not in f
    }
    used_bools = set(re.findall(r'flags\.has\("(--[a-z-]+)"\)', MAIN.read_text())) - GLOBAL_FLAGS
    if manifest_bools != used_bools:
        msg = []
        if used_bools - manifest_bools:
            msg.append("read via flags.has() in main.ts but not documented as boolean flags in commands.ts:\n  " + "\n  ".join(sorted(used_bools - manifest_bools)))
        if manifest_bools - used_bools:
            msg.append("documented as boolean flags in commands.ts but never read in main.ts:\n  " + "\n  ".join(sorted(manifest_bools - used_bools)))
        sys.exit("cli-docs: boolean flags out of sync —\n" + "\n".join(msg))

    read = env_vars()
    undocumented = sorted(read - set(ENV_DOCS))
    if undocumented:
        sys.exit(
            "cli-docs: these environment variables are read under cli/src but have no entry in "
            "ENV_DOCS in this script:\n  " + "\n  ".join(undocumented)
        )
    stale = sorted(set(ENV_DOCS) - read)
    if stale:
        sys.exit(
            "cli-docs: these entries in ENV_DOCS are no longer read anywhere under cli/src:\n  "
            + "\n  ".join(stale)
        )


def _synopsis_line(cmd: dict, sub: dict) -> str:
    parts = ["hg", cmd["name"]]
    if sub["name"]:
        parts.append(sub["name"])
    if sub.get("args"):
        parts.append(sub["args"])
    if sub.get("flags"):
        parts.append("[flags]")
    return " ".join(parts)


def _flags_table(flags: list[dict]) -> str:
    rows = ["| Flag | Value | Default | What it does |", "|---|---|---|---|"]
    for f in flags:
        value = f"`{f['value']}`" if f.get("value") else "—"
        default = f"`{f['default']}`" if f.get("default") else "—"
        rows.append(f"| `{f['name']}` | {value} | {default} | {f['desc']} |")
    return "\n".join(rows) + "\n"


def _examples(lines: list[str]) -> str:
    return "```bash\n" + "\n".join(lines) + "\n```\n"


def command_page(cmd: dict) -> str:
    out = [BANNER]
    out.append(f"# hg {cmd['name']}\n\n")
    out.append(
        f"**What this page tells you:** every `hg {cmd['name']}` "
        "subcommand, with its arguments, flags and defaults.\n\n"
    )
    out.append(cmd["summary"].capitalize().rstrip(".") + ".\n\n")
    out.append("## Synopsis\n\n```text\n")
    for sub in cmd["subs"]:
        out.append(_synopsis_line(cmd, sub) + "\n")
    out.append("```\n\n")
    if cmd.get("json"):
        out.append("`--json` prints one JSON document on stdout; narration goes to stderr.\n\n")
    if cmd.get("desc"):
        out.append("## Description\n\n" + cmd["desc"] + "\n\n")

    bare = len(cmd["subs"]) == 1 and not cmd["subs"][0]["name"]
    for sub in cmd["subs"]:
        if bare:
            # No subcommands: the page head already carries the summary; only
            # flags/examples remain to render.
            if sub.get("desc"):
                out.append(sub["desc"] + "\n\n")
            if sub.get("flags"):
                out.append("## Flags\n\n" + _flags_table(sub["flags"]) + "\n")
            if sub.get("examples"):
                out.append("## Examples\n\n" + _examples(sub["examples"]) + "\n")
            continue
        out.append(f"## `hg {cmd['name']} {sub['name']}`\n\n")
        out.append("```text\n" + _synopsis_line(cmd, sub) + "\n```\n\n")
        out.append(sub["summary"].capitalize().rstrip(".") + ".\n\n")
        if sub.get("desc"):
            out.append(sub["desc"] + "\n\n")
        if sub.get("flags"):
            out.append(_flags_table(sub["flags"]) + "\n")
        if sub.get("examples"):
            out.append("**Examples**\n\n" + _examples(sub["examples"]) + "\n")

    see = ["[Command index](index.md)"] + [f"[{_link_title(s)}]({s})" for s in cmd.get("see") or []]
    out.append("## See also\n\n" + "".join(f"- {s}\n" for s in see))
    return "".join(out)


def _link_title(rel: str) -> str:
    stem = pathlib.PurePosixPath(rel).stem
    return stem.replace("-", " ").capitalize()


JOURNEYS = [
    ("dev", "dev: build and run a team locally"),
    ("ops", "ops: host your own environment"),
    ("agent-bundle", "agent-bundle: author an Agent Team Repo, no cluster"),
    ("harness-legacy", "legacy harness (Hermes)"),
    ("all", "meta"),
]


def index_page(commands: list[dict]) -> str:
    # Grouped by primary journey, mirroring `hg --help`; the
    # grouping and the help output derive from the same manifest field, so
    # they cannot drift apart.
    out = [BANNER, INDEX_INTRO]
    # The loop front doors lead, mirroring `hg --help` (#673) - derived
    # from the manifest's frontDoor markers, never re-declared here.
    doors = []
    for c in commands:
        for sub in c.get("subs") or []:
            if sub.get("frontDoor"):
                cmd = " ".join(x for x in ["hg", c["name"], sub.get("name", "")] if x)
                loop0 = (c.get("loops") or ["?"])[0]
                doors.append(f"| [`{cmd}`]({c['name']}.md) | {loop0} | {sub['summary']} |\n")
    if doors:
        out.append("\n## Start here — one front door per loop\n\n")
        out.append("| Front door | Loop | What it does |\n|---|---|---|\n")
        out.extend(doors)
    for loop, title in JOURNEYS:
        members = [c for c in commands if (c.get("loops") or [None])[0] == loop]
        if not members:
            continue
        out.append(f"\n## {title}\n\n")
        out.append("| Command | Journeys | `--json` | What it does |\n|---|---|---|---|\n")
        for c in members:
            js = "yes" if c.get("json") else "—"
            loops = " · ".join(c.get("loops") or [])
            out.append(f"| [`hg {c['name']}`]({c['name']}.md) | {loops} | {js} | {c['summary']} |\n")
    out.append("\n## Environment variables\n\n")
    out.append("| Variable | What it does |\n|---|---|\n")
    for name in sorted(ENV_DOCS):
        out.append(f"| `{name}` | {ENV_DOCS[name]} |\n")
    out.append(INDEX_TAIL)
    return "".join(out)


def render_all() -> dict[pathlib.Path, str]:
    commands = manifest()
    check_coverage(commands)
    pages = {OUT_DIR / "index.md": index_page(commands)}
    for c in commands:
        pages[OUT_DIR / f"{c['name']}.md"] = command_page(c)
    return pages


def nav_snippet(pages: dict[pathlib.Path, str]) -> str:
    lines = ["      - CLI:", "          - Overview: reference/cli/index.md"]
    for p in sorted(pages):
        if p.name == "index.md":
            continue
        lines.append(f"          - hg {p.stem}: reference/cli/{p.name}")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the committed pages are stale")
    args = ap.parse_args()

    pages = render_all()
    existing = set(OUT_DIR.glob("*.md")) if OUT_DIR.exists() else set()
    strays = sorted(existing - set(pages))

    if not args.check:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for path, content in sorted(pages.items()):
            path.write_text(content)
        for s in strays:
            s.unlink()
            print(f"removed stray {s.relative_to(ROOT)}")
        print(f"wrote {len(pages)} pages under {OUT_DIR.relative_to(ROOT)}")
        print("nav (mkdocs.yml, hand-maintained — paste under Reference):")
        print(nav_snippet(pages))
        return

    stale: list[str] = []
    for path, content in sorted(pages.items()):
        have = path.read_text() if path.exists() else ""
        if have != content:
            stale.append(str(path.relative_to(ROOT)))
            sys.stdout.writelines(
                difflib.unified_diff(
                    have.splitlines(True), content.splitlines(True),
                    fromfile=str(path), tofile="generated", n=2,
                )
            )
    for s in strays:
        stale.append(f"{s.relative_to(ROOT)} (stray — no such command)")
    if stale:
        sys.exit("\ncli-docs: stale pages — run `make cli-docs`:\n  " + "\n  ".join(stale))


if __name__ == "__main__":
    main()
