apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermes-bundle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    hermes-gitops.factorylevel.dev/plane: workload
    hermes-gitops.factorylevel.dev/component: hermes-bundle
    {{- include "hermes-bundle.labels" . | nindent 4 }}
