apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels: {hermes-gitops.factorylevel.dev/plane: control-plane, hermes-gitops.factorylevel.dev/component: nexus, app.kubernetes.io/name: nexus}
spec:
  selector: {app.kubernetes.io/name: nexus}
  ports:
    - port: 80
      targetPort: 8080
