// The app-of-apps root: an Argo CD Application named "hermes-gitops-root"
// whose source is the GitOps repo's `bootstrap/` directory — i.e. it syncs
// `project.yaml` (the AppProject) and `applicationset.yaml` (which then
// fans out into one Application per installed agent persona). This is the
// one resource in bootstrap stage 3 that hands control over to Argo CD /
// GitOps for everything downstream.
//
// The control-flow layer gates this component off entirely (never
// constructs it) when the configured gitopsRepoUrl is a placeholder — see
// gitopsRepoIsPlaceholder in control-flow/config.ts. This matters for
// stage-3-only verification runs: stage 2 (which actually populates a real
// GitOps repo with `bootstrap/project.yaml` etc.) hasn't run yet, so
// pointing a real Application at a real-looking-but-empty-or-nonexistent
// repo would just sit permanently Unknown/Missing for no useful signal.
// When a real gitopsRepoUrl is configured (the production path), this
// Application is created normally; Argo CD is welcome to report a
// missing/unreachable repo on its own terms if the operator's config is
// wrong — that's real signal bootstrap shouldn't swallow.

import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";
import { Namespaces, ARGOCD_NS } from "../namespaces/index.ts";

export const APP_NAME = "hermes-gitops-root";

// The root Application ALWAYS syncs the app-of-apps into the control
// plane itself, even in a multi-cluster fleet (issue #8 [C2]) — remote
// placement happens one level down, at the ApplicationSet's per-record
// destination. Named so the intent is explicit, not a bare literal.
export const IN_CLUSTER_SERVER = "https://kubernetes.default.svc";

export interface RootAppArgs {
  provider: k8s.Provider;
  namespaces: Namespaces;
  gitopsRepoUrl: string;
  gitopsBranch: string;
  argocdRelease: k8s.helm.v3.Release;
  // Lets the control-flow layer fold in the rest of stage 3's resources
  // (secret-store/pulumi-operator: namespaces -> {argocd, eso} ->
  // {secret-store, pulumi-operator} -> root-app) without this component
  // needing to import or know about any of them directly. Conditionally
  // absent ones (e.g. PKO when the ingress provider doesn't need it) are
  // expected to already be filtered out by the caller.
  extraDependsOn?: pulumi.Resource[];
}

export class RootApp extends pulumi.ComponentResource {
  readonly app: k8s.apiextensions.CustomResource;

  constructor(name: string, args: RootAppArgs, opts?: pulumi.ComponentResourceOptions) {
    super("hermes-gitops:bootstrap:RootApp", name, {}, opts);

    this.app = new k8s.apiextensions.CustomResource(
      "hermes-gitops-root-app",
      {
        apiVersion: "argoproj.io/v1alpha1",
        kind: "Application",
        metadata: { name: APP_NAME, namespace: ARGOCD_NS },
        spec: {
            // NOT "hermes-gitops": that AppProject is itself created by this
            // Application's own sync (bootstrap/project.yaml, in the same
            // source dir as applicationset.yaml). Referencing it here
            // would be a bootstrapping deadlock — Argo CD can't
            // admit/reconcile an Application whose project doesn't exist
            // yet, and the project can't be created until this Application
            // successfully syncs. "default" is Argo CD's always-present
            // built-in AppProject; only the per-persona Applications
            // generated by hermes-gitops-profiles (once "hermes-gitops"
            // exists) use it.
            project: "default",
            source: {
              repoURL: args.gitopsRepoUrl,
              targetRevision: args.gitopsBranch,
              path: "bootstrap",
              // RECURSE (#759): the template keeps the ApplicationSets in
              // bootstrap/applicationsets/, and a root app that applies
              // only the top level never deploys them - the 2026-08-27
              // fleet-down incident was exactly this mismatch (the legacy
              // top-level copies were the only live appsets, and pruning
              // them cascaded the fleet away).
              //
              // EXCLUDE the staged-not-promoted generators: recursion must
              // not silently promote them. apps/bundles/endpoints are
              // halted pending #498/#516 (the SAME-COMMIT contract in
              // apps.yaml's header - promoting apps without flipping
              // appsManagedExternally on the agents AppSet is a
              // two-controller prune/adopt fight over the child apps,
              // found live 2026-08-28). applicationset.yaml is the legacy
              // hermes-gitops-profiles generator, retired at the wave-3
              // cutover; its template file exists only so the scaffold
              // reconciler refuses ad-hoc recreation.
              directory: {
                recurse: true,
                exclude:
                  "{applicationset.yaml,applicationsets/apps.yaml,applicationsets/bundles.yaml,applicationsets/endpoints.yaml}",
              },
            },
            destination: {
              server: IN_CLUSTER_SERVER,
              namespace: ARGOCD_NS,
            },
            syncPolicy: {
              automated: { prune: true, selfHeal: true },
              syncOptions: ["CreateNamespace=true", "ServerSideApply=true"],
              retry: {
                limit: 5,
                backoff: { duration: "30s", factor: 2, maxDuration: "5m" },
              },
            },
        },
      },
      {
        parent: this,
        provider: args.provider,
        dependsOn: [
          args.namespaces.argocd,
          args.argocdRelease,
          ...(args.extraDependsOn ?? []),
        ],
      },
    );

    this.registerOutputs({});
  }
}
