import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { parse, stringify } from "yaml";
import { CliError } from "../lib.ts";
import { digest, immutableRef, type TeamPlan, type TeamSource } from "./plan.ts";
import { assertAllowedRuntimes, effectiveRuntime } from "./runtime.ts";

/** The bootstrap-owned record of exactly what a version-2 installation publishes (ADR 0190): the
 * commit behind every source ref, and the runtime every agent deploys on (version 2, ADR 0192). */
export interface InstallationLock {
  /** Version 1 locks (sources only) still verify and publish; `hg team compile` writes version 2. */
  version: 1 | 2;
  installation: string;
  planDigest: string;
  sources: Record<string, { ref: string; commit: string }>;
  /** Version 2: every agent in the plan, by name - the effective image and Eve release. */
  agents?: Record<string, { image: string; eveVersion: string }>;
  /** Version 2, when the plan declares one: the platform revision this installation runs, and
   * the one it replaces - the pair a rollback needs (ADR 0193). */
  platform?: { ref: string; revision: string; previousRevision?: string };
}
export const LOCK_HEADER = "# Generated by `hg team compile` from the installation plan. Do not hand-edit:\n# change the plan, compile again, review, and commit both.\n";
const commit = /^[a-f0-9]{40}$/;
const fail = (message: string): never => { throw new CliError(`installation lock: ${message}`); };

/** The lock is bound to one exact plan document; any plan change needs a new compile. */
export function planDigest(plan: TeamPlan): string {
  return digest(plan);
}

export function validateLock(input: unknown): InstallationLock {
  const lock = input as InstallationLock;
  if (!lock || typeof lock !== "object" || Array.isArray(lock)) fail("must be a mapping");
  const keys = Object.keys(lock).sort().join(",");
  if (lock.version === 1) {
    if (keys !== "installation,planDigest,sources,version") fail("version 1 carries exactly version, installation, planDigest and sources");
  } else if (lock.version === 2) {
    if (!["agents,installation,planDigest,sources,version", "agents,installation,planDigest,platform,sources,version"].includes(keys)) fail("version 2 carries exactly version, installation, planDigest, sources, agents and an optional platform");
  } else fail("requires version 1 or 2");
  if (typeof lock.installation !== "string" || !lock.installation) fail("installation required");
  if (typeof lock.planDigest !== "string" || !/^[a-f0-9]{64}$/.test(lock.planDigest)) fail("planDigest must be a SHA-256 digest");
  if (!lock.sources || typeof lock.sources !== "object" || Array.isArray(lock.sources)) fail("sources must be a mapping");
  for (const [id, entry] of Object.entries(lock.sources)) {
    if (!entry || typeof entry !== "object" || Object.keys(entry).sort().join(",") !== "commit,ref") fail(`source ${id} carries exactly ref and commit`);
    if (typeof entry.ref !== "string" || !immutableRef(entry.ref)) fail(`source ${id}: ref must be refs/tags/<tag> or a full commit`);
    if (typeof entry.commit !== "string" || !commit.test(entry.commit) || /^0+$/.test(entry.commit)) fail(`source ${id}: commit must be a full SHA`);
    if (commit.test(entry.ref) && entry.ref !== entry.commit) fail(`source ${id}: a commit ref locks to itself`);
  }
  if (lock.version === 1) return lock;
  if (lock.platform !== undefined) {
    const platform = lock.platform;
    if (!platform || typeof platform !== "object" || Array.isArray(platform) || !["ref,revision", "previousRevision,ref,revision"].includes(Object.keys(platform).sort().join(","))) fail("platform carries exactly ref, revision and an optional previousRevision");
    if (typeof platform.ref !== "string" || !immutableRef(platform.ref)) fail("platform ref must be refs/tags/<tag> or a full commit");
    if (typeof platform.revision !== "string" || !commit.test(platform.revision) || /^0+$/.test(platform.revision)) fail("platform revision must be a full SHA");
    if (commit.test(platform.ref) && platform.ref !== platform.revision) fail("a platform commit ref locks to itself");
    if (platform.previousRevision !== undefined && (!commit.test(platform.previousRevision) || /^0+$/.test(platform.previousRevision))) fail("platform previousRevision must be a full SHA");
    if (platform.previousRevision === platform.revision) fail("platform previousRevision must differ from the revision it replaces");
  }
  if (!lock.agents || typeof lock.agents !== "object" || Array.isArray(lock.agents)) fail("agents must be a mapping");
  for (const [name, entry] of Object.entries(lock.agents!)) {
    if (!entry || typeof entry !== "object" || Object.keys(entry).sort().join(",") !== "eveVersion,image") fail(`agent ${name} carries exactly image and eveVersion`);
    if (typeof entry.image !== "string" || !/^\S+@sha256:[a-f0-9]{64}$/.test(entry.image)) fail(`agent ${name}: image must be pinned by digest`);
    if (typeof entry.eveVersion !== "string" || !/^[0-9]+\.[0-9]+\.[0-9]+(?:-[\w.]+)?$/.test(entry.eveVersion)) fail(`agent ${name}: eveVersion must be the Eve release its image ships`);
  }
  return lock;
}

/** Deterministic bytes: the same resolution always renders the same lock. */
export function renderLock(lock: InstallationLock): string {
  if (lock.version !== 2 || !lock.agents) throw new CliError("Only a version 2 installation lock is rendered; run hg team compile");
  const sources = Object.fromEntries(Object.keys(lock.sources).sort().map(id => [id, { ref: lock.sources[id]!.ref, commit: lock.sources[id]!.commit }]));
  const agents = Object.fromEntries(Object.keys(lock.agents).sort().map(name => [name, { image: lock.agents![name]!.image, eveVersion: lock.agents![name]!.eveVersion }]));
  const platform = lock.platform && { ref: lock.platform.ref, revision: lock.platform.revision,
    ...(lock.platform.previousRevision ? { previousRevision: lock.platform.previousRevision } : {}) };
  return LOCK_HEADER + stringify({ version: 2, installation: lock.installation, planDigest: lock.planDigest, sources, agents, ...(platform ? { platform } : {}) }, { lineWidth: 0 });
}

export function readLock(file: string): InstallationLock {
  if (!fs.existsSync(file)) throw new CliError("Installation lock is missing; run hg team compile and commit the lock beside the plan");
  return validateLock(parse(fs.readFileSync(file, "utf8")));
}

/** A bootstrap-relative lock path whose directory stays inside the bootstrap checkout. */
export function lockPath(root: string, relative: string): string {
  const realRoot = fs.realpathSync(root);
  const target = path.resolve(realRoot, relative);
  if (!fs.existsSync(path.dirname(target))) throw new CliError("Installation lock directory does not exist in the bootstrap checkout");
  const parent = fs.realpathSync(path.dirname(target));
  if (parent !== realRoot && !parent.startsWith(`${realRoot}${path.sep}`)) throw new CliError("Installation lock resolves outside the bootstrap checkout");
  const file = path.join(parent, path.basename(target));
  let isLink = false;
  try { isLink = fs.lstatSync(file).isSymbolicLink(); } catch { /* absent: compile creates it */ }
  if (isLink) throw new CliError("Installation lock must not be a symbolic link");
  return file;
}

/** Write through an exclusively created temporary file, then rename: never follows or reuses an
 * entry someone planted beside the lock. */
export function writeLockFile(file: string, text: string, suffix: string = randomUUID()): void {
  const tmp = `${file}.${suffix}.tmp`;
  let fd: number;
  try { fd = fs.openSync(tmp, "wx", 0o644); }
  catch { throw new CliError("Installation lock temporary file already exists; remove stray files beside the lock and compile again"); }
  try { fs.writeFileSync(fd, text); } finally { fs.closeSync(fd); }
  fs.renameSync(tmp, file);
}

/** Refuse a lock that no longer describes this plan. */
export function verifyLock(plan: TeamPlan, lock: InstallationLock): void {
  if (lock.installation !== plan.id) throw new CliError("Installation lock belongs to a different installation");
  if (lock.planDigest !== planDigest(plan)) throw new CliError("Installation lock is stale: the plan changed after it was compiled; run hg team compile, review the result, and commit both");
  if (plan.sources.map(s => s.id).sort().join("\n") !== Object.keys(lock.sources).sort().join("\n")) throw new CliError("Installation lock does not cover exactly the plan's sources; run hg team compile");
  for (const source of plan.sources) if (lock.sources[source.id]!.ref !== source.ref) throw new CliError(`Installation lock records a different ref for source ${source.id}; run hg team compile`);
  if ((plan.platform?.ref ?? null) !== (lock.platform?.ref ?? null)) {
    throw new CliError("Installation lock records a different platform revision than the plan declares; run hg team compile, review the result, and commit both");
  }
  const agents = plan.sources.flatMap(s => s.agents);
  if (lock.version === 1) {
    // A lock compiled before runtimes were recorded still governs every source commit. It cannot
    // vouch for a runtime pin, so a plan that has one needs a recompile before it deploys.
    const pinned = agents.filter(a => a.runtime).map(a => a.name);
    if (pinned.length) throw new CliError(`Installation lock predates per-agent runtimes and cannot vouch for the pin on ${pinned.join(", ")}; run hg team compile, review the result, and commit both`);
    console.error("installation lock: version 1 records no runtimes; run hg team compile to record the runtime every agent deploys on");
    return;
  }
  if (agents.map(a => a.name).sort().join("\n") !== Object.keys(lock.agents!).sort().join("\n")) throw new CliError("Installation lock does not cover exactly the plan's agents; run hg team compile");
  for (const agent of agents) {
    // A runtime pin that never reached the lock would deploy something nobody reviewed.
    const runtime = effectiveRuntime(plan, agent), locked = lock.agents![agent.name]!;
    if (locked.image !== runtime.image || locked.eveVersion !== runtime.eveVersion) throw new CliError(`Installation lock records a different runtime for ${agent.name}; run hg team compile, review the result, and commit both`);
  }
}

/** The locked commit for a source, refusing a ref that now resolves elsewhere (a moved tag). */
export function lockedCommit(lock: InstallationLock, source: TeamSource, resolved: string): string {
  const entry = lock.sources[source.id];
  if (!entry) throw new CliError(`Installation lock has no entry for source ${source.id}; run hg team compile`);
  if (resolved !== entry.commit) throw new CliError(`Source ${source.id}: ${source.ref} now resolves to ${resolved.slice(0, 12)}, not the locked ${entry.commit.slice(0, 12)}; review the moved tag, then run hg team compile`);
  return entry.commit;
}

/** What resolving a ref actually needs - a team source satisfies it, and so does the platform. */
export type RefTarget = Pick<TeamSource, "id" | "repository" | "ref" | "private"> & { credentialEnv?: string };
export type RefResolver = (target: RefTarget) => Promise<string>;

/** Resolve every source ref once and bind the result to this exact plan. */
export async function compileLock(plan: TeamPlan, resolve: RefResolver, previous?: InstallationLock): Promise<InstallationLock> {
  if (plan.version !== 2) throw new CliError("hg team compile requires installation plan version 2");
  assertAllowedRuntimes(plan);
  const sources: InstallationLock["sources"] = {};
  for (const source of plan.sources) {
    const resolved = (await resolve(source)).trim();
    if (!commit.test(resolved) || /^0+$/.test(resolved)) throw new CliError(`Source ${source.id}: ref did not resolve to a commit`);
    if (commit.test(source.ref) && resolved !== source.ref) throw new CliError(`Source ${source.id}: commit ref resolved to a different commit`);
    sources[source.id] = { ref: source.ref, commit: resolved };
  }
  const agents: InstallationLock["agents"] = {};
  for (const source of plan.sources) for (const agent of source.agents) agents[agent.name] = effectiveRuntime(plan, agent);
  let platform: InstallationLock["platform"];
  if (plan.platform) {
    // `platform~` cannot be a source id (ids are [a-z][a-z0-9-]*), so resolving the platform can
    // never collide with a source's scratch clone - including a source literally named "platform".
    const revision = (await resolve({ id: "platform~", repository: plan.platform.repository, ref: plan.platform.ref,
      private: Boolean(plan.platform.credentialEnv), credentialEnv: plan.platform.credentialEnv })).trim();
    if (!commit.test(revision) || /^0+$/.test(revision)) throw new CliError("Platform: ref did not resolve to a commit");
    if (commit.test(plan.platform.ref) && revision !== plan.platform.ref) throw new CliError("Platform: commit ref resolved to a different commit");
    // The revision being replaced is what a rollback returns to; re-compiling at the same
    // revision keeps whatever the lock already recorded rather than erasing it.
    const prior = previous?.platform;
    const previousRevision = prior && prior.revision !== revision ? prior.revision : prior?.previousRevision;
    platform = { ref: plan.platform.ref, revision, ...(previousRevision && previousRevision !== revision ? { previousRevision } : {}) };
  }
  return validateLock({ version: 2, installation: plan.id, planDigest: planDigest(plan), sources, agents, ...(platform ? { platform } : {}) });
}
