apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    hermes-gitops.factorylevel.dev/plane: control-plane
    hermes-gitops.factorylevel.dev/component: loki
    app.kubernetes.io/name: loki
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    - {name: http, port: 3100, targetPort: http}
